export { Sequence } from "./sequence";
export { AnalogSettings } from "./analogSettings";
export { Groups } from "./groups";
export { T2Settings } from "./t2Settings";
export { DVBCSettings } from "./dvbcSettings";
export { IPTVSettings } from "./iptvSettings";
export { Devices } from "./devices";
export { Schedules } from "./schedules";
export { Login } from "./login";
// export { UserRegister } from "./register";
export { Main } from "./main";
export { TablePage } from "./table";
export { Video } from "./video";
export { ChartPage } from "./chartPage";
export { Compare } from "./compare";
export { UserRegister } from "./userRegister";
